### ISSUE TITLE
n_shared estimation

### ISSUE THREAD

**Issue by j-bac** [caokai1073/Pamona#2]
Thanks a lot for the tool and didactic notebooks ! I did not find an example showing how to estimate the number of shared cells, would you have one to provide ?

**Comment by caokai1073** [comment]
Thanks for your interest. The shared cell number is a prior parameter which needs to be given before the computation. But if a dataset A is a subset of another dataset B, then the shared cell number is the number of A. If A and B both have dataset-specific cells, the shared cell number need to be known. And if you don't know the number, you can try the SPL method we proposed to estimate the shared cell number based on the algorithm. See Supplementary Note 4 of our paper: https://doi.org/10.1093/bioinformatics/btab594
